# Generated by Django 4.2.16 on 2024-10-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeupArtist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupartistprofile',
            name='Details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
