# Generated by Django 4.2.16 on 2024-11-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0002_alter_payment_userlid'),
        ('TeamEvent', '0003_alter_cateringservice_evelid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='USERLID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eventuserbookings', to='User_Profile.user_table'),
        ),
    ]
