# Generated by Django 4.2.16 on 2024-11-12 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamEvent', '0004_alter_eventbooking_userlid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='USERLID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eventuserbookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
